version: "3.1"

services:
    database:
        image: postgres:13.3
        restart: always
        ports: [ "5432:5432" ]
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        logging:
            driver: "none"

    adminer:
        image: adminer:4.8.1
        restart: always
        ports: [ "8081:8080" ]
        logging:
            driver: "none"